# --------------------------------------------------------------
version_major_number: '3'
version_minor_number: '2'
version_suffix: 'alpha'
version_string: '3.2alpha'
version_type: 'unstable'
# --------------------------------------------------------------
core_name: 'Unitex'
ide_name: 'GramLab'
pack_name: 'Unitex-GramLab'
name: 'Unitex/GramLab'
logo: '/user/unitexgramlab.png'
# --------------------------------------------------------------
author_name: 'The Unitex/GramLab authors'
publisher_name: 'Université Paris-Est Marne-la-Vallée'
copyright_holder_name: 'Université Paris-Est Marne-la-Vallée'
# --------------------------------------------------------------
license_sources:  'LGPL'
license_resources: 'LGPLLR'
# --------------------------------------------------------------
url_releases: 'http://releases.unitexgramlab.org'
url_vinber: 'http://unitexgramlab.org/v6'
url_vinber_info: 'http://unitexgramlab.org/v6/#bundle=nightly&q=latest-deployed&line=1'
url_version_json: 'http://unitexgramlab.org/v6/badge/nightly/latest-deployed.json?subject=build.finished&status=product.version.string'
url_support: 'mailto:unitex-devel@univ-mlv.fr'
url_license_sources: 'https://opensource.org/licenses/lgpl-2.1'
url_license_resources: 'http://unitexgramlab.org/lgpllr'
# --------------------------------------------------------------
release_file: "Unitex-GramLab-3.2alpha{suffix}"
release_link: "http://releases.unitexgramlab.org/3.2alpha/{arch}/Unitex-GramLab-3.2alpha{suffix}"
# --------------------------------------------------------------
release_linux32: 'http://releases.unitexgramlab.org/3.2alpha/linux-i686/Unitex-GramLab-3.2alpha-linux-i686.run'
release_linux64: 'http://releases.unitexgramlab.org/3.2alpha/linux-x86_64/Unitex-GramLab-3.2alpha-linux-x86_64.run'
release_osx:     'http://releases.unitexgramlab.org/3.2alpha/osx/Unitex-GramLab-3.2alpha-osx.run'
release_win32:   'http://releases.unitexgramlab.org/3.2alpha/win32/Unitex-GramLab-3.2alpha_win32-setup.exe'
release_win64:   'http://releases.unitexgramlab.org/3.2alpha/win64/Unitex-GramLab-3.2alpha_win64-setup.exe'
release_other:   'http://releases.unitexgramlab.org/3.2alpha/source/Unitex-GramLab-3.2alpha-source-distribution.zip'
release_manual:  'http://releases.unitexgramlab.org/3.2alpha/man/Unitex-GramLab-3.2alpha-usermanual-'
# --------------------------------------------------------------
usermanual_langs: [ en, fr ]
# --------------------------------------------------------------
